#!/usr/bin/env python3
# encoding: utf-8
"""
motor_response_sweep.py — Jupiter 모터별 응답비 측정 (Layer 1 / FF 보정용)

목적
    각 cmd vx (전·후진), cmd ω (좌·우 회전) 의 다양한 값에 대해 각 모터의
    실제 출력 (wheel_speeds 정상 구간 평균) 을 측정 → 응답비 표 (calibration yaml).
    이 표를 펌웨어 Feed-Forward 보정 (Layer 2) 의 입력으로 사용한다.

실행 전 가정
    - jupiter_driver_compensated 노드 동작 중 ( /cmd_vel_safe publish, /jupiter/wheel_speeds 받음 )
    - 로봇 jack-up 또는 빈 공간 (전후 2m, 좌우 1m)
    - twist_mux 우선순위에서 joy=100, force=80, nav=50.
      이 스크립트는 priority 100 의 /cmd_vel_joy 로 발행하여 collision_monitor bypass.

매핑 메모
    - /jupiter/wheel_speeds.data[0] = 펌웨어 wL 라벨 = 실제 우측 휠 (M1)
    - /jupiter/wheel_speeds.data[1] = 펌웨어 wR 라벨 = 실제 좌측 휠 (M3)
    - MCU 부호 convention: 전진 = 음수, 후진 = 양수 (driver line 671 주석)
    - 실제 모터 속도 (ROS frame) = -wL (M1), -wR (M3)

산출물
    /home/jetson/jupiter_ws_ros2/scripts/motor_calibration.yaml
"""

import os
import sys
import time
import argparse
import statistics
from collections import deque

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from std_msgs.msg import Float32MultiArray


CMD_TOPIC   = '/cmd_vel_joy'    # twist_mux 의 joy priority (collision_monitor bypass)
WHEEL_TOPIC = '/jupiter/wheel_speeds'

# sweep targets
VX_LIST = [0.10, 0.15, 0.20, 0.25, 0.30, -0.10, -0.15, -0.20, -0.25, -0.30]
WZ_LIST = [0.5, 0.8, 1.2, 1.5, -0.5, -0.8, -1.2, -1.5]

HOLD_SEC       = 3.0    # 한 step 유지 시간
SETTLE_SEC     = 1.2    # 시작 후 무시 (가속 transient)
WHEEL_RATE_HZ  = 25     # /jupiter/wheel_speeds 갱신율
ZERO_BETWEEN_S = 1.0    # 각 step 사이 정지 시간 (정지 안정화)
PUB_RATE_HZ    = 50


class SweepNode(Node):
    def __init__(self):
        super().__init__('motor_response_sweep')
        self.pub = self.create_publisher(Twist, CMD_TOPIC, 10)
        self.wheel_buf = deque(maxlen=int(WHEEL_RATE_HZ * (HOLD_SEC + 0.5)))
        self.sub = self.create_subscription(
            Float32MultiArray, WHEEL_TOPIC, self.wheel_cb, 10)

    def wheel_cb(self, msg: Float32MultiArray):
        # (timestamp_s, wL, wR)
        self.wheel_buf.append((time.monotonic(), msg.data[0], msg.data[1]))

    def publish_zero(self, dur_s):
        t_end = time.monotonic() + dur_s
        msg = Twist()
        period = 1.0 / PUB_RATE_HZ
        while time.monotonic() < t_end:
            self.pub.publish(msg)
            rclpy.spin_once(self, timeout_sec=period)

    def publish_hold(self, vx, wz, dur_s):
        """vx, wz 값을 dur_s 동안 발행하면서 wheel_buf 채움"""
        t_end = time.monotonic() + dur_s
        msg = Twist()
        msg.linear.x = float(vx)
        msg.angular.z = float(wz)
        period = 1.0 / PUB_RATE_HZ
        while time.monotonic() < t_end:
            self.pub.publish(msg)
            rclpy.spin_once(self, timeout_sec=period)

    def measure_step(self, vx, wz, label):
        """한 step 측정: 정지 → 명령 발행 → settle 후 평균 → 정지"""
        self.wheel_buf.clear()
        self.publish_zero(ZERO_BETWEEN_S)

        self.get_logger().info(f"  [{label}] cmd vx={vx:+.3f}, wz={wz:+.3f} ({HOLD_SEC}s)")
        t_start = time.monotonic()
        self.publish_hold(vx, wz, HOLD_SEC)
        t_stop = time.monotonic()

        # SETTLE_SEC 이후 ~ t_stop 사이의 평균
        settle_after = t_start + SETTLE_SEC
        wL_samples = [s[1] for s in self.wheel_buf if settle_after <= s[0] <= t_stop]
        wR_samples = [s[2] for s in self.wheel_buf if settle_after <= s[0] <= t_stop]

        n = len(wL_samples)
        if n < 5:
            self.get_logger().warn(f"    샘플 부족 (N={n}). step skip.")
            self.publish_zero(ZERO_BETWEEN_S)
            return None

        wL_mean = statistics.mean(wL_samples)
        wR_mean = statistics.mean(wR_samples)
        wL_std  = statistics.pstdev(wL_samples)
        wR_std  = statistics.pstdev(wR_samples)

        # 실제 모터 속도 (ROS frame): -wL (M1=실 우), -wR (M3=실 좌)
        v_M1 = -wL_mean
        v_M3 = -wR_mean

        result = {
            'cmd_vx': vx,
            'cmd_wz': wz,
            'wL_mean': wL_mean,  # 펌웨어 라벨 wL = 실제 우 M1 (MCU 부호)
            'wR_mean': wR_mean,
            'wL_std':  wL_std,
            'wR_std':  wR_std,
            'v_M1':    v_M1,     # ROS frame, M1=실제 우
            'v_M3':    v_M3,     # ROS frame, M3=실제 좌
            'N':       n,
        }
        self.get_logger().info(
            f"    M1(실우) v={v_M1:+.4f}  M3(실좌) v={v_M3:+.4f}  N={n}")
        self.publish_zero(ZERO_BETWEEN_S)
        return result


def write_yaml(results_vx, results_wz, out_path):
    with open(out_path, 'w') as f:
        f.write("# motor_calibration.yaml — Layer 1 측정 결과\n")
        f.write(f"# Generated by motor_response_sweep.py at {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("# 좌표/라벨 매핑:\n")
        f.write("#   M1 = 실제 우측 휠 (펌웨어 wL 라벨)\n")
        f.write("#   M3 = 실제 좌측 휠 (펌웨어 wR 라벨)\n")
        f.write("#   v_M* 는 ROS frame (전진=+, 후진=-)\n")
        f.write("#\n")
        f.write("# 응답비 정의: v_actual / cmd. 1.0 = 명령대로. <1 = 명령보다 느림.\n")
        f.write("# Layer 2 FF gain = 1 / 응답비 (inverse).\n\n")

        # linear sweep
        f.write("linear_sweep:\n")
        for r in results_vx:
            if r is None: continue
            ratio_M1 = r['v_M1'] / r['cmd_vx'] if abs(r['cmd_vx']) > 0.001 else 0
            ratio_M3 = r['v_M3'] / r['cmd_vx'] if abs(r['cmd_vx']) > 0.001 else 0
            dir_label = "fwd" if r['cmd_vx'] > 0 else "bwd"
            f.write(f"  - cmd_vx: {r['cmd_vx']:+.3f}    # {dir_label}\n")
            f.write(f"    v_M1: {r['v_M1']:+.4f}\n")
            f.write(f"    v_M3: {r['v_M3']:+.4f}\n")
            f.write(f"    M1_ratio: {ratio_M1:.4f}\n")
            f.write(f"    M3_ratio: {ratio_M3:.4f}\n")
            f.write(f"    M1_FF_gain: {1.0/ratio_M1:.4f}\n" if abs(ratio_M1)>0.01 else "    M1_FF_gain: 1.0\n")
            f.write(f"    M3_FF_gain: {1.0/ratio_M3:.4f}\n" if abs(ratio_M3)>0.01 else "    M3_FF_gain: 1.0\n")
            f.write(f"    wL_std: {r['wL_std']:.4f}\n")
            f.write(f"    wR_std: {r['wR_std']:.4f}\n")
            f.write(f"    N: {r['N']}\n")

        # angular sweep
        f.write("\nangular_sweep:\n")
        for r in results_wz:
            if r is None: continue
            dir_label = "ccw" if r['cmd_wz'] > 0 else "cw"
            f.write(f"  - cmd_wz: {r['cmd_wz']:+.3f}    # {dir_label}\n")
            f.write(f"    v_M1: {r['v_M1']:+.4f}\n")
            f.write(f"    v_M3: {r['v_M3']:+.4f}\n")
            f.write(f"    abs_M1: {abs(r['v_M1']):.4f}\n")
            f.write(f"    abs_M3: {abs(r['v_M3']):.4f}\n")
            f.write(f"    sym_pct: {(abs(r['v_M1'])-abs(r['v_M3']))/((abs(r['v_M1'])+abs(r['v_M3']))/2)*100:.2f}\n" if (abs(r['v_M1'])+abs(r['v_M3']))>0.01 else "    sym_pct: 0\n")
            f.write(f"    wL_std: {r['wL_std']:.4f}\n")
            f.write(f"    wR_std: {r['wR_std']:.4f}\n")
            f.write(f"    N: {r['N']}\n")

        # 평균 FF gain — 방향 별 평균
        f.write("\n# ============================================================\n")
        f.write("# 권장 FF gain (방향 별 평균) — Layer 2 펌웨어 코드 직접 입력용\n")
        f.write("# ============================================================\n")
        def avg_ff(side, direction):
            vals = []
            for r in results_vx:
                if r is None: continue
                is_fwd = r['cmd_vx'] > 0
                if direction == 'fwd' and not is_fwd: continue
                if direction == 'bwd' and is_fwd: continue
                v = r['v_M1'] if side == 'M1' else r['v_M3']
                if abs(r['cmd_vx']) > 0.05:
                    ratio = v / r['cmd_vx']
                    if abs(ratio) > 0.1:
                        vals.append(1.0 / ratio)
            return statistics.mean(vals) if vals else 1.0
        f.write("recommended_ff_gains:\n")
        f.write(f"  M1_FWD: {avg_ff('M1','fwd'):.4f}\n")
        f.write(f"  M1_BWD: {avg_ff('M1','bwd'):.4f}\n")
        f.write(f"  M3_FWD: {avg_ff('M3','fwd'):.4f}\n")
        f.write(f"  M3_BWD: {avg_ff('M3','bwd'):.4f}\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', default='/home/jetson/jupiter_ws_ros2/scripts/motor_calibration.yaml')
    parser.add_argument('--skip-angular', action='store_true', help="각속도 sweep 생략")
    parser.add_argument('--skip-linear', action='store_true', help="선속도 sweep 생략")
    args = parser.parse_args()

    rclpy.init()
    node = SweepNode()
    print("\n" + "="*72)
    print(" Jupiter Motor Response Sweep")
    print("="*72)
    print(f"  cmd topic   : {CMD_TOPIC}  (twist_mux joy priority 100)")
    print(f"  wheel topic : {WHEEL_TOPIC}")
    print(f"  output yaml : {args.out}")
    print(f"  vx steps    : {VX_LIST}")
    print(f"  wz steps    : {WZ_LIST}")
    print(f"  hold/step   : {HOLD_SEC}s  settle: {SETTLE_SEC}s")
    print("="*72)
    print("\n!! 안전 확인: 로봇 잭업 또는 빈 공간 (전후 2m). 5초 후 시작.\n")
    try:
        for i in range(5, 0, -1):
            print(f"  {i}...", end='', flush=True); time.sleep(1)
        print("  go!")
    except KeyboardInterrupt:
        node.destroy_node(); rclpy.shutdown(); return

    results_vx = []
    results_wz = []
    try:
        if not args.skip_linear:
            print(f"\n[Phase 1/2] linear sweep ({len(VX_LIST)} steps)")
            for vx in VX_LIST:
                results_vx.append(node.measure_step(vx, 0.0, f"vx={vx:+.2f}"))

        if not args.skip_angular:
            print(f"\n[Phase 2/2] angular sweep ({len(WZ_LIST)} steps)")
            for wz in WZ_LIST:
                results_wz.append(node.measure_step(0.0, wz, f"wz={wz:+.2f}"))
    except KeyboardInterrupt:
        print("\n[!] 사용자 중단 — 지금까지 측정 저장")
    finally:
        node.publish_zero(0.5)

    write_yaml(results_vx, results_wz, args.out)
    print(f"\n[*] 결과 저장: {args.out}")

    # 요약 출력
    print("\n" + "="*72)
    print(" 요약")
    print("="*72)
    for r in results_vx:
        if r is None: continue
        rM1 = r['v_M1']/r['cmd_vx'] if abs(r['cmd_vx'])>0.001 else 0
        rM3 = r['v_M3']/r['cmd_vx'] if abs(r['cmd_vx'])>0.001 else 0
        print(f"  vx={r['cmd_vx']:+.3f}  M1/cmd={rM1:.3f}  M3/cmd={rM3:.3f}  "
              f"FF: M1={1/rM1 if abs(rM1)>0.1 else 1:.3f} M3={1/rM3 if abs(rM3)>0.1 else 1:.3f}")
    for r in results_wz:
        if r is None: continue
        magR, magL = abs(r['v_M1']), abs(r['v_M3'])
        sym = (magR-magL)/((magR+magL)/2)*100 if (magR+magL)>0.01 else 0
        print(f"  wz={r['cmd_wz']:+.3f}  |M1|={magR:.3f} |M3|={magL:.3f}  sym={sym:+.2f}%")

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
